const topics=()=>[{id:'numbers',name:'Số học',color:'#2176ff'},{id:'algebra',name:'Đại số',color:'#16b3d8'},{id:'geometry',name:'Hình học',color:'#ffbc35'},{id:'statistics',name:'Thống kê, xác suất',color:'#20b88b'},{id:'other',name:'Chủ đề khác',color:'#ed5aa0'}].map(t=>({...t,total:0,correct:0}));
export function parentSummary({state,catalog,report,child,children,days=7,now=Date.now()}){
 days=[7,30].includes(Number(days))?Number(days):7;
 const day=86400000,offset=7*3600000,start=Math.floor((now+offset)/day)*day-offset-(days-1)*day;
 const topicOf=a=>/area|angles|pythagoras|trig|circle/.test(a.skill)?'geometry':/sign|fractions|percent|ratio/.test(a.skill)?'numbers':/distribute|combine|equation|identity|roots|systems|quadratic/.test(a.skill)?'algebra':/xác suất|thống kê/i.test(catalog.find(e=>e.id===a.exerciseId)?.topic||'')?'statistics':'other';
 const current=state.attempts.filter(a=>a.time>=start&&a.time<=now),previous=state.attempts.filter(a=>a.time>=start-days*day&&a.time<start);
 const groups=topics();for(const a of current){const t=groups.find(t=>t.id===topicOf(a));t.total++;if(a.initialCorrect)t.correct++;}
 const accuracy=rows=>rows.length?Math.round(rows.filter(a=>a.initialCorrect).length/rows.length*100):null;
 const trend=Array.from({length:days},(_,i)=>{const time=start+i*day,end=Math.min(now,time+day-1),rows=current.filter(a=>a.time<=end);return{time,label:new Date(time+offset).toISOString().slice(5,10).split('-').reverse().join('/'),values:Object.fromEntries(groups.map(t=>[t.id,accuracy(rows.filter(a=>topicOf(a)===t.id))]))};});
 const assigned=report.assignments,total=assigned.reduce((n,a)=>n+a.result.total,0),answered=assigned.reduce((n,a)=>n+a.result.answered,0),checked=report.comparisons.filter(c=>c.after),verified=checked.filter(c=>c.after.correct).length;
 const errors=report.errors.filter(e=>e.count).map(e=>{const count=rows=>rows.filter(a=>!a.initialCorrect&&e.attemptIds.includes(a.id)).length;return{...e,current:count(current),previous:count(previous)};});
 const pending=assigned.filter(a=>!a.result.complete).sort((a,b)=>a.due.localeCompare(b.due));
 const events=[...assigned.map(a=>({id:'assignment-'+a.id,time:a.created,title:a.title,detail:`${a.result.answered}/${a.result.total} câu đã làm · Hạn ${a.due.split('-').reverse().join('/')}`,view:'assignments',kind:'assignment'})),...state.attempts.map(a=>({id:a.id,time:a.completed||a.time,title:a.completed?'Con đã hoàn thành một lượt học':a.initialCorrect?'Con có đáp án đầu đúng':'Có bài làm cần xem lại',detail:catalog.find(e=>e.id===a.exerciseId)?.prompt||'Bài đã học',view:a.initialCorrect?'results':'errors',kind:a.initialCorrect?'result':'error'}))].sort((a,b)=>b.time-a.time).slice(0,20);
 return{child,children,days,topics:groups,trend,average:assigned.length?Math.round(assigned.reduce((n,a)=>n+a.result.score,0)/assigned.length*10)/10:null,completion:total?Math.round(answered/total*100):null,totalQuestions:total,answered,assignments:assigned,pending,wrong:report.evidence.length,errors,progress:checked.length<3?'Đang theo dõi':verified/checked.length>=2/3?'Đang tiến bộ':'Cần củng cố',checked:checked.length,verified,accuracy:accuracy(current),accuracyChange:current.length>=3&&previous.length>=3?accuracy(current)-accuracy(previous):null,reviewCount:state.attempts.filter(a=>a.mode==='review').length,reviewCorrect:state.attempts.filter(a=>a.mode==='review'&&a.initialCorrect).length,dueReviews:Object.values(state.reviews||{}).filter(r=>r.due<=now).length,events,latest:state.attempts.reduce((n,a)=>Math.max(n,a.completed||a.time),0),comparisons:report.comparisons};
}
