import {createTestApp} from './browser-fixture.mjs';
const testApp=await createTestApp({grade:9});
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1366,height:900}});
const page=await context.newPage();const errors=[];
page.on('pageerror',e=>errors.push(e.message));
try{
  await testApp.login(page);
  await page.route('**/api/status',route=>route.fulfill({json:{ai:true,model:'mock'}}));
  await page.route('**/api/explain',route=>route.fulfill({json:{source:'gemini',feedback:String.raw`Em đã biết trừ hai vế. Kiểm chứng: \(\frac{9}{3}+2=5\). Căn ví dụ: \(\sqrt{9}=3\). Hệ: \[\begin{cases}x+y=5\\x-y=1\end{cases}\] <img src=x onerror=alert(1)>`,needsTeacher:true}}));
  await page.goto(testApp.base+'/#formulas');await page.locator('.atlas-list').waitFor({state:'attached'});
  assert.equal(await page.locator('.atlas-list .formula-item').count(),6);
  assert.equal(await page.locator('.math-fallback, .katex-error').count(),0);
  assert.ok(await page.locator('mfrac').count()>0);assert.ok(await page.locator('msqrt').count()>0);assert.ok(await page.locator('mtable').count()>0);
  await page.evaluate(()=>document.fonts.ready);
  assert.ok(await page.evaluate(()=>document.fonts.check('16px KaTeX_Main')));
  await page.goto(testApp.base+'/#learn/equation-6');
  assert.equal(await page.locator('.problem mfrac').count(),1);
  await page.locator('#answer').fill('1/2');
  assert.equal(await page.locator('.math-preview mfrac').count(),1);
  await page.screenshot({path:'artifacts/math-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Kiểm tra đáp án'}).click();
  await page.locator('[data-diagnosis="1"]').click();await page.locator('[data-next]').click();
  await page.locator('#correction').fill('9');await page.getByRole('button',{name:'Kiểm tra cách sửa'}).click();
  await page.locator('#explanation').fill(String.raw`Em trừ 2 ở hai vế, được \(\frac{x}{3}=3\). Nhân hai vế với 3 được x = 9.`);
  await page.locator('.math-writing-help summary').click();assert.equal(await page.locator('.math-preview-text mfrac').count(),1);
  await page.locator('#explanation-form button:not([type])').click();await page.locator('[data-finish]').waitFor();
  assert.ok(await page.locator('.feedback mfrac').count()>0);assert.ok(await page.locator('.feedback msqrt').count()>0);
  assert.equal(await page.locator('.feedback img').count(),0);
  assert.equal(await page.locator('.feedback .math-fallback').count(),0);
  await page.locator('[data-finish]').click();
  await page.goto(testApp.base+'/#notebook');assert.ok(await page.locator('.list-row mfrac').count()>0);
  await page.setViewportSize({width:390,height:844});
  await page.goto(testApp.base+'/#formulas');await page.locator('.atlas-list').waitFor({state:'attached'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'artifacts/math-mobile.png',fullPage:true});
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.locator('.formula-item').first().waitFor();
  await context.setOffline(true);await page.locator('.formula-item').first().waitFor();
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.math-fallback,.katex-error').count(),0);
  assert.ok(await page.evaluate(()=>document.fonts.check('16px KaTeX_Main')));
  assert.ok(await page.locator('mfrac').count()>0);
  assert.deepEqual(errors,[]);
  console.log('PASS: fractions, roots, systems, input previews, mocked Gemini LaTeX, escaped HTML, saved notebook, mobile and offline fonts.');
}finally{await browser.close();await testApp.close();}
